# Generated by Django 3.2.8 on 2021-11-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='details',
            field=models.CharField(max_length=200),
        ),
    ]
